@baseUrl = http://localhost:5001
@urlPath = api/v1

###
GET {{baseUrl}}/{{urlPath}}/chat/message/conversation-list
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/chat/message/user/66d48542582f3ed7993dc7a0
Content-Type: application/json
Accept: application/json
withCredentials: true

###
POST {{baseUrl}}/{{urlPath}}/chat/message
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "conversationId": "66f3a1688db12b765e127a68",
  "receiverId": "66d48542582f3ed7993dc7a0",
  "receiverUsername": "Saifu3",
  "receiverAvatarColor": "blue",
  "receiverProfilePicture": "https://res.cloudinary.com/dhhiyrhfh/image/upload/v1725863311/66de958d32180d3a0d91ade7",
  "body": "Hello da",
  "gifUrl": "",
  "isRead": false,
  "selectedImage": ""
}

###
POST {{baseUrl}}/{{urlPath}}/chat/message/add-chat-users
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userOne": "66d48542582f3ed7993dc7a0",
  "userTwo": "66d48511582f3ed7993dc792"
}

###
POST {{baseUrl}}/{{urlPath}}/chat/message/remove-chat-users
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userOne": "66d48542582f3ed7993dc7a0",
  "userTwo": "66d48511582f3ed7993dc792"
}

###
PUT {{baseUrl}}/{{urlPath}}/chat/message/mark-as-read
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "senderId": "66d48511582f3ed7993dc792",
  "receiverId": "66d48542582f3ed7993dc7a0"
}

###
PUT {{baseUrl}}/{{urlPath}}/chat/message/reaction
Content-Type: application/json
Accept: application/json
withCredentials: true

# For this endpoint, the type is either add or remove
{
  "conversationId": "66f3a1688db12b765e127a68",
  "messageId": "66f3a1688db12b765e127a67",
  "reaction": "love",
  "type": "remove"
}

###
DELETE {{baseUrl}}/{{urlPath}}/chat/message/mark-as-deleted/66f3a801f1951b2b4b865260/66d48511582f3ed7993dc792/66d48542582f3ed7993dc7a0/deleteForEveryone
# For this endpoint, the type is either deleteForMe or deleteForEveryone
Content-Type: application/json
Accept: application/json
withCredentials: true
